"""initial relational schema

Revision ID: 645cd7ed22d8
Revises: 
Create Date: 2026-08-19 14:16:51.936919
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '645cd7ed22d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('public_email', sa.String(length=320), nullable=True),
    sa.Column('public_phone', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practices_name'), 'practices', ['name'], unique=False)
    op.create_index(op.f('ix_practices_slug'), 'practices', ['slug'], unique=True)
    op.create_table('procedures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_procedures_category'), 'procedures', ['category'], unique=False)
    op.create_index(op.f('ix_procedures_name'), 'procedures', ['name'], unique=True)
    op.create_table('rating_dimensions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('surgeons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=240), nullable=False),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('specialty', sa.String(length=240), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('public_contact', sa.Text(), nullable=True),
    sa.Column('portrait_media_id', sa.Uuid(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_revision_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['current_revision_id'], ['surgeon_revisions.id'], name='fk_surgeons_current_revision', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['portrait_media_id'], ['media_assets.id'], name='fk_surgeons_portrait_media', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surgeons_country_code'), 'surgeons', ['country_code'], unique=False)
    op.create_index(op.f('ix_surgeons_display_name'), 'surgeons', ['display_name'], unique=False)
    op.create_index(op.f('ix_surgeons_is_published'), 'surgeons', ['is_published'], unique=False)
    op.create_index(op.f('ix_surgeons_slug'), 'surgeons', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('member', 'trusted_editor', 'moderator', 'admin', name='userrole'), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('approximate_region', sa.String(length=160), nullable=True),
    sa.Column('allow_messages', sa.Boolean(), nullable=False),
    sa.Column('allow_new_accounts', sa.Boolean(), nullable=False),
    sa.Column('email_message_notifications', sa.Boolean(), nullable=False),
    sa.Column('email_watch_notifications', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_display_name'), 'users', ['display_name'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('account_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_account_tokens_expires_at'), 'account_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_account_tokens_purpose'), 'account_tokens', ['purpose'], unique=False)
    op.create_index(op.f('ix_account_tokens_user_id'), 'account_tokens', ['user_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('public_detail', sa.Text(), nullable=True),
    sa.Column('private_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_table('conversation_members',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'user_id')
    )
    op.create_table('email_outbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipient_user_id', sa.Uuid(), nullable=False),
    sa.Column('template', sa.String(length=80), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_outbox_next_attempt_at'), 'email_outbox', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_email_outbox_recipient_user_id'), 'email_outbox', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_email_outbox_state'), 'email_outbox', ['state'], unique=False)
    op.create_index(op.f('ix_email_outbox_template'), 'email_outbox', ['template'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('practice_id', sa.Uuid(), nullable=True),
    sa.Column('label', sa.String(length=160), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('accessibility', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_country_code'), 'locations', ['country_code'], unique=False)
    op.create_index(op.f('ix_locations_practice_id'), 'locations', ['practice_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('safe_storage_key', sa.String(length=500), nullable=True),
    sa.Column('media_type', sa.String(length=100), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('processing_state', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('safe_storage_key'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_media_assets_owner_id'), 'media_assets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_media_assets_sha256'), 'media_assets', ['sha256'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reporter_id', sa.Uuid(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_reports_state'), 'reports', ['state'], unique=False)
    op.create_index(op.f('ix_reports_target_id'), 'reports', ['target_id'], unique=False)
    op.create_index(op.f('ix_reports_target_type'), 'reports', ['target_type'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('publisher', sa.String(length=240), nullable=True),
    sa.Column('archived_url', sa.String(length=2048), nullable=True),
    sa.Column('accessed_on', sa.Date(), nullable=True),
    sa.Column('supports', sa.Text(), nullable=True),
    sa.Column('submitted_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surgeon_practices',
    sa.Column('surgeon_id', sa.Uuid(), nullable=False),
    sa.Column('practice_id', sa.Uuid(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['surgeon_id'], ['surgeons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('surgeon_id', 'practice_id')
    )
    op.create_table('surgeon_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('surgeon_id', sa.Uuid(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('parent_revision_id', sa.Uuid(), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('article_body', sa.Text(), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('edit_summary', sa.String(length=500), nullable=False),
    sa.Column('change_type', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.Enum('normal', 'reviewed', 'rollback', name='revisionkind'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_revision_id'], ['surgeon_revisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['surgeon_id'], ['surgeons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('surgeon_id', 'revision_number')
    )
    op.create_index('ix_revisions_surgeon_published', 'surgeon_revisions', ['surgeon_id', 'published_at'], unique=False)
    op.create_index(op.f('ix_surgeon_revisions_author_id'), 'surgeon_revisions', ['author_id'], unique=False)
    op.create_index(op.f('ix_surgeon_revisions_change_type'), 'surgeon_revisions', ['change_type'], unique=False)
    op.create_index(op.f('ix_surgeon_revisions_published_at'), 'surgeon_revisions', ['published_at'], unique=False)
    op.create_index(op.f('ix_surgeon_revisions_surgeon_id'), 'surgeon_revisions', ['surgeon_id'], unique=False)
    op.create_table('talk_topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('surgeon_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.Enum('draft', 'pending', 'published', 'rejected', 'hidden', name='moderationstate'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['surgeon_id'], ['surgeons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('surgeon_id', 'slug')
    )
    op.create_index(op.f('ix_talk_topics_surgeon_id'), 'talk_topics', ['surgeon_id'], unique=False)
    op.create_table('techniques',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('procedure_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('procedure_id', 'name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_techniques_name'), 'techniques', ['name'], unique=False)
    op.create_index(op.f('ix_techniques_procedure_id'), 'techniques', ['procedure_id'], unique=False)
    op.create_table('user_blocks',
    sa.Column('blocker_id', sa.Uuid(), nullable=False),
    sa.Column('blocked_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blocker_id', 'blocked_id')
    )
    op.create_table('edit_proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('surgeon_id', sa.Uuid(), nullable=False),
    sa.Column('base_revision_id', sa.Uuid(), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('proposed_article_body', sa.Text(), nullable=False),
    sa.Column('proposed_snapshot_json', sa.Text(), nullable=False),
    sa.Column('edit_summary', sa.String(length=500), nullable=False),
    sa.Column('state', sa.Enum('draft', 'pending', 'published', 'rejected', 'hidden', name='moderationstate'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['base_revision_id'], ['surgeon_revisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['surgeon_id'], ['surgeons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edit_proposals_author_id'), 'edit_proposals', ['author_id'], unique=False)
    op.create_index(op.f('ix_edit_proposals_state'), 'edit_proposals', ['state'], unique=False)
    op.create_index(op.f('ix_edit_proposals_surgeon_id'), 'edit_proposals', ['surgeon_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('surgeon_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('procedure_id', sa.Uuid(), nullable=False),
    sa.Column('technique_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('surgery_date', sa.Date(), nullable=True),
    sa.Column('surgery_date_precision', sa.String(length=12), nullable=False),
    sa.Column('location_country_code', sa.String(length=2), nullable=True),
    sa.Column('location_text', sa.String(length=240), nullable=True),
    sa.Column('cost_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_currency', sa.String(length=3), nullable=True),
    sa.Column('cost_includes', sa.Text(), nullable=True),
    sa.Column('wait_time_days', sa.Integer(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('complications_status', sa.String(length=40), nullable=False),
    sa.Column('complications_detail', sa.Text(), nullable=True),
    sa.Column('revision_detail', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('draft', 'pending', 'published', 'rejected', 'hidden', name='moderationstate'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['surgeon_id'], ['surgeons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['technique_id'], ['techniques.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_procedure_id'), 'reviews', ['procedure_id'], unique=False)
    op.create_index(op.f('ix_reviews_published_at'), 'reviews', ['published_at'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_reviews_slug'), 'reviews', ['slug'], unique=True)
    op.create_index(op.f('ix_reviews_state'), 'reviews', ['state'], unique=False)
    op.create_index(op.f('ix_reviews_surgeon_id'), 'reviews', ['surgeon_id'], unique=False)
    op.create_index('ix_reviews_surgeon_state_published', 'reviews', ['surgeon_id', 'state', 'published_at'], unique=False)
    op.create_table('revision_sources',
    sa.Column('revision_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['surgeon_revisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('revision_id', 'source_id')
    )
    op.create_table('surgeon_procedures',
    sa.Column('surgeon_id', sa.Uuid(), nullable=False),
    sa.Column('procedure_id', sa.Uuid(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('citation_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['citation_id'], ['sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['surgeon_id'], ['surgeons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('surgeon_id', 'procedure_id')
    )
    op.create_table('talk_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('parent_comment_id', sa.Uuid(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('draft', 'pending', 'published', 'rejected', 'hidden', name='moderationstate'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['talk_comments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['talk_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_talk_comments_topic_id'), 'talk_comments', ['topic_id'], unique=False)
    op.create_table('proposal_sources',
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['edit_proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('proposal_id', 'source_id')
    )
    op.create_table('review_photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('capture_date', sa.Date(), nullable=True),
    sa.Column('capture_date_precision', sa.String(length=12), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('visibility', sa.Enum('public', 'members', 'private', name='visibility'), nullable=False),
    sa.Column('content_warning', sa.String(length=240), nullable=True),
    sa.Column('designated_long_term', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media_assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id')
    )
    op.create_index(op.f('ix_review_photos_review_id'), 'review_photos', ['review_id'], unique=False)
    op.create_table('review_ratings',
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('dimension_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dimension_id'], ['rating_dimensions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id', 'dimension_id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_ratings')
    op.drop_index(op.f('ix_review_photos_review_id'), table_name='review_photos')
    op.drop_table('review_photos')
    op.drop_table('proposal_sources')
    op.drop_index(op.f('ix_talk_comments_topic_id'), table_name='talk_comments')
    op.drop_table('talk_comments')
    op.drop_table('surgeon_procedures')
    op.drop_table('revision_sources')
    op.drop_index('ix_reviews_surgeon_state_published', table_name='reviews')
    op.drop_index(op.f('ix_reviews_surgeon_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_state'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_slug'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_published_at'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_procedure_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_edit_proposals_surgeon_id'), table_name='edit_proposals')
    op.drop_index(op.f('ix_edit_proposals_state'), table_name='edit_proposals')
    op.drop_index(op.f('ix_edit_proposals_author_id'), table_name='edit_proposals')
    op.drop_table('edit_proposals')
    op.drop_table('user_blocks')
    op.drop_index(op.f('ix_techniques_procedure_id'), table_name='techniques')
    op.drop_index(op.f('ix_techniques_name'), table_name='techniques')
    op.drop_table('techniques')
    op.drop_index(op.f('ix_talk_topics_surgeon_id'), table_name='talk_topics')
    op.drop_table('talk_topics')
    op.drop_index(op.f('ix_surgeon_revisions_surgeon_id'), table_name='surgeon_revisions')
    op.drop_index(op.f('ix_surgeon_revisions_published_at'), table_name='surgeon_revisions')
    op.drop_index(op.f('ix_surgeon_revisions_change_type'), table_name='surgeon_revisions')
    op.drop_index(op.f('ix_surgeon_revisions_author_id'), table_name='surgeon_revisions')
    op.drop_index('ix_revisions_surgeon_published', table_name='surgeon_revisions')
    op.drop_table('surgeon_revisions')
    op.drop_table('surgeon_practices')
    op.drop_table('sources')
    op.drop_index(op.f('ix_reports_target_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_target_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_state'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_media_assets_sha256'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_owner_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_locations_practice_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_country_code'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_email_outbox_template'), table_name='email_outbox')
    op.drop_index(op.f('ix_email_outbox_state'), table_name='email_outbox')
    op.drop_index(op.f('ix_email_outbox_recipient_user_id'), table_name='email_outbox')
    op.drop_index(op.f('ix_email_outbox_next_attempt_at'), table_name='email_outbox')
    op.drop_table('email_outbox')
    op.drop_table('conversation_members')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_account_tokens_user_id'), table_name='account_tokens')
    op.drop_index(op.f('ix_account_tokens_purpose'), table_name='account_tokens')
    op.drop_index(op.f('ix_account_tokens_expires_at'), table_name='account_tokens')
    op.drop_table('account_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_display_name'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_surgeons_slug'), table_name='surgeons')
    op.drop_index(op.f('ix_surgeons_is_published'), table_name='surgeons')
    op.drop_index(op.f('ix_surgeons_display_name'), table_name='surgeons')
    op.drop_index(op.f('ix_surgeons_country_code'), table_name='surgeons')
    op.drop_table('surgeons')
    op.drop_table('rating_dimensions')
    op.drop_index(op.f('ix_procedures_name'), table_name='procedures')
    op.drop_index(op.f('ix_procedures_category'), table_name='procedures')
    op.drop_table('procedures')
    op.drop_index(op.f('ix_practices_slug'), table_name='practices')
    op.drop_index(op.f('ix_practices_name'), table_name='practices')
    op.drop_table('practices')
    op.drop_table('conversations')
    # ### end Alembic commands ###

